// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANnZ33zSFUPaVKV-jHNeKeI_D7V8ZLK84',
    appId: '1:681625931457:web:943d1d6ed44975cb4d8e40',
    messagingSenderId: '681625931457',
    projectId: 'provadaora',
    authDomain: 'provadaora.firebaseapp.com',
    storageBucket: 'provadaora.firebasestorage.app',
    measurementId: 'G-CZJVV68EWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKlmSVfeCFHFkazpBO1X2JstjU9l7OdlA',
    appId: '1:681625931457:android:aeb90ea96af40ecf4d8e40',
    messagingSenderId: '681625931457',
    projectId: 'provadaora',
    storageBucket: 'provadaora.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANnZ33zSFUPaVKV-jHNeKeI_D7V8ZLK84',
    appId: '1:681625931457:web:4dde9a8545fb727a4d8e40',
    messagingSenderId: '681625931457',
    projectId: 'provadaora',
    authDomain: 'provadaora.firebaseapp.com',
    storageBucket: 'provadaora.firebasestorage.app',
    measurementId: 'G-S4X3C042VY',
  );
}
